run: build
	bash run.sh

build:
	bash build.sh


#build_lib:
	#mkdir -p ${LIB_DIR}
	#${CC} -c ${SOURCES}
	#ar rc ${LIB_DIR}/lib${NAME}.a *.o
	#ranlib ${LIB_DIR}/lib${NAME}.a
	#${MAKE} clean

clean:
	bash clean.sh